#!/bin/bash -l
#
#Number of cores requested
#$ -pe omp 12

#Give the name to the job
#$ -N BLAST_LCA_cluster

#Output file destination
#$ -o outputs/$JOB_NAME.o$JOB_ID

#Send an email when the job is finished (or aborted)
#$ -M enpederson@gmail.com
#$ -m ae


#Join the error and output file
#$ -j y


# Set the runtime limit (default 16 hours):
#$ -l h_rt=16:00:00

# Specify your project
#$ -P ct-shbioinf


# Stuff to execute: 

module load blast+ #load blast module
module load sratoolkit
module load R/3.6.2 #load R3.6.2

cd /projectnb/ct-shbioinf/epederso/bioinf_final/ #use your notes or project folder. Wherever your script is located

Rscript 'scripts/Full_script.R' #run the script